"""Added two new columns to virtual machines

Revision ID: 13b46ae6ddc7
Revises: 92bc1cd6dffe
Create Date: 2025-01-01 12:15:40.246788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b46ae6ddc7'
down_revision = '92bc1cd6dffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_base_vm', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('cloned_from', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('idx_proxmox_id'), ['proxmox_id'], unique=False) # This line is new
        batch_op.create_index(batch_op.f('ix_virtual_machines_cloned_from'), ['cloned_from'], unique=False)

        batch_op.create_foreign_key(
            'fk_virtual_machines_cloned_from', 
            'virtual_machines',
            ['cloned_from'],
            ['proxmox_id'],
            ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_virtual_machines_cloned_from', type_='foreignkey')
        batch_op.drop_index(batch_op.f('idx_proxmox_id')) # This line is new
        batch_op.drop_index(batch_op.f('ix_virtual_machines_cloned_from'))
        batch_op.drop_column('cloned_from')
        batch_op.drop_column('is_base_vm')

    # ### end Alembic commands ###
