"""Added constraint to labs

Revision ID: 1711d9d9bd4a
Revises: 647e345e0432
Create Date: 2024-12-29 11:42:08.877989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1711d9d9bd4a'
down_revision = '647e345e0432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_laboratorio_nombre_asignatura_id', ['nombre', 'asignatura_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_laboratorio_nombre_asignatura_id', type_='unique')

    # ### end Alembic commands ###
