"""Change lab_id to subject_id on the virtual machines table

Revision ID: 2a15901e74c4
Revises: c003b4ae5ffb
Create Date: 2024-12-25 13:08:06.613059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a15901e74c4'
down_revision = 'c003b4ae5ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignatura_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('virtual_machines_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asignaturas', ['asignatura_id'], ['id'])
        batch_op.drop_column('laboratorio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratorio_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('virtual_machines_ibfk_1', 'laboratorios', ['laboratorio_id'], ['id'])
        batch_op.drop_column('asignatura_id')

    # ### end Alembic commands ###
