"""Cascade delete for horarios

Revision ID: 3a1e096d6f8c
Revises: d88f5504e9bc
Create Date: 2025-01-05 18:35:52.412790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1e096d6f8c'
down_revision = 'd88f5504e9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_constraint('horarios_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asignaturas', ['asignatura_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
    #     batch_op.drop_index('idx_proxmox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
    #     batch_op.create_index('idx_proxmox_id', ['proxmox_id'], unique=False)

    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('horarios_ibfk_1', 'asignaturas', ['asignatura_id'], ['id'])

    # ### end Alembic commands ###
