"""Added on cascade delete to the labs

Revision ID: 647e345e0432
Revises: 2a15901e74c4
Create Date: 2024-12-27 20:47:26.131955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647e345e0432'
down_revision = '2a15901e74c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_constraint('laboratorios_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asignaturas', ['asignatura_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('laboratorios_ibfk_1', 'asignaturas', ['asignatura_id'], ['id'])

    # ### end Alembic commands ###
