"""Created table Matriculas

Revision ID: 7e6b47e26de5
Revises: 307d6df7d0bb
Create Date: 2024-12-15 11:16:06.300432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6b47e26de5'
down_revision = '307d6df7d0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriculas',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_matricula', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignaturas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'asignatura_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matriculas')
    # ### end Alembic commands ###
