"""PDF url added to the labs

Revision ID: 92bc1cd6dffe
Revises: 1711d9d9bd4a
Create Date: 2024-12-30 10:55:55.459287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bc1cd6dffe'
down_revision = '1711d9d9bd4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
