"""Add cascading deletes for matriculas

Revision ID: a56e1a5235da
Revises: 7e6b47e26de5
Create Date: 2024-12-15 14:02:50.790079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56e1a5235da'
down_revision = '7e6b47e26de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_constraint('matriculas_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('matriculas_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asignaturas', ['asignatura_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('matriculas_ibfk_1', 'asignaturas', ['asignatura_id'], ['id'])
        batch_op.create_foreign_key('matriculas_ibfk_2', 'usuarios', ['user_id'], ['id'])

    # ### end Alembic commands ###
