"""Added constraint to Asignaturas

Revision ID: a714a4bdf004
Revises: 3a1e096d6f8c
Create Date: 2025-01-07 14:09:07.576180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a714a4bdf004'
down_revision = '3a1e096d6f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
