"""virtual_machines tables modified

Revision ID: c003b4ae5ffb
Revises: a56e1a5235da
Create Date: 2024-12-24 18:39:23.752479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c003b4ae5ffb'
down_revision = 'a56e1a5235da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guacamole_connection_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['guacamole_connection_id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('guacamole_connection_id')

    # ### end Alembic commands ###
