"""Added nombre_usuario to Usuario's table. Will be used for Guacamole connections and other checks

Revision ID: c668d16e821b
Revises: 636111715d39
Create Date: 2024-12-01 11:20:43.144634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c668d16e821b'
down_revision = '636111715d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_usuario', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nombre_usuario')

    # ### end Alembic commands ###
