"""Created horarios table

Revision ID: d88f5504e9bc
Revises: f0fe6767e984
Create Date: 2025-01-05 13:24:26.705990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88f5504e9bc'
down_revision = 'f0fe6767e984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo', name='dia_semana'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dia', 'hora_inicio', 'hora_fin', 'asignatura_id', name='uq_horario_por_asignatura')
    )
    # with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
    #     batch_op.drop_index('idx_proxmox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
    #     batch_op.create_index('idx_proxmox_id', ['proxmox_id'], unique=False)

    op.drop_table('horarios')
    # ### end Alembic commands ###
