"""vnc credentials on virtual machines

Revision ID: f0fe6767e984
Revises: ba6251103013
Create Date: 2025-01-05 12:05:12.940372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fe6767e984'
down_revision = '13b46ae6ddc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vnc_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vnc_password', sa.Text(), nullable=True))
        # batch_op.drop_index('idx_proxmox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        # batch_op.create_index('idx_proxmox_id', ['proxmox_id'], unique=False)
        batch_op.drop_column('vnc_password')
        batch_op.drop_column('vnc_username')

    # ### end Alembic commands ###
